font_family Maple Mono Italic

# Make the cursor shape a beam
shell_integration no-cursor
cursor_shape beam

# Padding
window_padding_width 7
window_padding_height 10

# Default font size.
font_size 11

# Just a keybind to change font size to your liking, it's CTRL + scroll wheel up or down.
map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

# Background opacity, set to 0 if you want blur/transparency.
# Blur works with hyprland, or sway-fx as a drop-in replacement for sway.
background_opacity 0.75

# Everforest Dark Hard - kitty color theme

background           #1e2326
foreground           #d3c6aa
selection_background #3a454a
selection_foreground #d3c6aa

# The cursor matches the moss green for high visibility
cursor               #a7c080
cursor_text_color    #1e2326

# URL underline color (Bioluminescent teal)
url_color            #7fbbb3

# Black
color0               #414b50
color8               #475258
# Red (Crimson Spore - used for errors)
color1               #e67e80
color9               #e67e80
# Green (Moss Emerald - used for success/strings)
color2               #a7c080
color10              #a7c080
# Yellow (Warm Amber)
color3               #dbbc7f
color11              #dbbc7f
# Blue (Deep glowing teal)
color4               #7fbbb3
color12              #7fbbb3
# Magenta (Dusky Orchid)
color5               #d699b6
color13              #d699b6
# Cyan (Bioluminescent Cyan)
color6               #83c092
color14              #83c092
# White (Warm Parchment)
color7               #d3c6aa
color15              #d3c6aa
